---
- name: FABRIC BUILD
  hosts: all
  gather_facts: false
  vars_files:
    - group_vars/nxos.yml

  tasks:
    - name: "Enable OSPF feature"
      nxos_feature:
        feature: ospf
        state: enabled

    - name: "Create OSPF instance"
      cisco.nxos.nxos_ospf:
        config:
          processes:
            - process_id: 1
              router_id: "{{ hostvars[inventory_hostname]['lo0_ipaddr'] }}"
              address_family:
                areas:
                  - area_id: 0
              vrfs:
                - vrf: management
                  router_id: "{{ hostvars[inventory_hostname]['ansible_host'] }}"
                  areas:
                    - area_id: 0
        state: merged

    - name: "Enable interface OSPF (eth)"
      cisco.nxos.nxos_ospf_interfaces:
        config:
          - name: "Ethernet 2/{{item}}"
            address_family:
              - afi: ipv4
                processes:
                  - process_id: "1"
                    area:
                      area_id: 0
        state: merged
      with_sequence: start=1 end="{{ hostvars[inventory_hostname]['eth_range_end'] }}"

    - name: "Enable interface OSPF (lo0)"
      cisco.nxos.nxos_ospf_interfaces:
        config:
          - name: "Loopback 0"
            address_family:
              - afi: ipv4
                processes:
                  - process_id: "1"
                    area:
                      area_id: 0
        state: merged

    - name: "Set Lo0"
      nxos_interfaces:
        config:
          - name: Loopback 0
            enable: true
            description: "Configured by Ansible"

    - name: "Set Lo0 ip"
      nxos_l3_interfaces:
        config:
          - name: Loopback 0
            ipv4:
              - address: "{{ hostvars[inventory_hostname]['lo0_ipaddr'] }}"
        state: merged

    - name: "Set ethernet ports"
      nxos_interfaces:
        config:
          - name: "Ethernet 2/{{item}}"
            enable: true
            description: "Configured by Ansible"
            mode: layer3
            mtu: 9216
        state: merged
      with_sequence: start=1 end="{{ hostvars[inventory_hostname]['eth_range_end'] }}"

    - name: "Set interface to p2p and unnummbered"
      nxos_config:
        lines:
          - medium p2p
          - ip unnumbered loopback 0
        before:
          - "interface ethernet 2/{{item}}"
      with_sequence: start=1 end="{{ hostvars[inventory_hostname]['eth_range_end'] }}"
