- name: FABRIC TEST
  hosts: all
  gather_facts: false
  vars_files:
    - group_vars/nxos.yml

  tasks:
    - name: "Check Connectivity (ping)"
      nxos_ping:
        source: "{{ hostvars[inventory_hostname]['lo0_ipaddr'] }}"
        vrf: default
        dest: "192.168.1.{{item}}"
      with_sequence: start=1 end=10
      register: out

    - debug:
        msg:
          - "command: {{ out.results[item|int].commands[0]}}"
          - "rtt: {{ out.results[item|int].rtt}}"
          - "pktloss: {{ out.results[item|int].packet_loss}}"
      with_sequence: start=0 end=9
