---
- name: FABRIC BUILD
  hosts: all
  gather_facts: false
  vars_files:
    - group_vars/nxos.yml

  tasks:
    - name: "Enable OSPF feature"
      nxos_feature:
        feature: ospf
        state: enabled

    - name: "Create OSPF instance"
      nxos_ospf:
        ospf: 1
        state: present

    - name: "Enable interface OSPF (eth)"
      nxos_interface_ospf:
        interface: "ethernet 2/{{item}}"
        ospf: 1
        area: 0
      with_sequence: start=1 end="{{ hostvars[inventory_hostname]['eth_range_end'] }}"

    - name: "Enable interface OSPF (lo0)"
      nxos_interface_ospf:
        interface: lo0
        ospf: 1
        area: 0

    - name: "Set Lo0"
      nxos_interface:
        name: Loopback 0
        state: present

    - name: "Set Lo0 ip"
      nxos_l3_interface:
        name: Loopback 0
        ipv4: "{{ hostvars[inventory_hostname]['lo0_ipaddr'] }}/32"
        state: present

    - name: "Set ethernet ports"
      nxos_interface:
        name: "ethernet 2/{{item}}"
        state: present
        mode: layer3
        mtu: 9216
      with_sequence: start=1 end="{{ hostvars[inventory_hostname]['eth_range_end'] }}"

    - name: "Set interface to p2p and unnummbered"
      nxos_config:
        lines:
          - medium p2p
          - ip unnumbered lo0
        before:
          - "interface ethernet 2/{{item}}"
      with_sequence: start=1 end="{{ hostvars[inventory_hostname]['eth_range_end'] }}"
